server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    config:
      enabled: false  # Assuming you don't have a config server setup for this service
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/customer/**
          filters:
            - name: AuthenticationFilter
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/devices/**
          filters:
            - name: AuthenticationFilter
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/customer/fund/**
          filters:
            - name: AuthenticationFilter
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/account/**
          filters:
            - name: AuthenticationFilter
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/billPayment/**
          filters:
            - name: AuthenticationFilter
        - id: otp-service
          uri: lb://otp-service
          predicates:
            - Path=/v1/otp/**
          filters:
            - name: AuthenticationFilter
        - id: add-payee
          uri: lb://add-payee
          predicates:
            - Path=/v1/beneficiary/**
          filters:
            - name: AuthenticationFilter
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v1/settings/**
          filters:
            - name: AuthenticationFilter


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8772/eureka/

logging:
  level:
    root: INFO
    com.iconsult.apigateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG