# Server settings
server:
  port: 8090


# Database configuration
spring:
  application:
    name: ADD-PAYEE
  datasource:
    url: jdbc:postgresql://192.168.0.196:5432/mydatabase
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8772/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true