# Server settings
server:
  port: 8088



# Database configuration
spring:
#  kafka:
#    topic:
#      name: otp-topic
#    producer:
#      bootstrap-servers: kafka:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://192.168.0.196:5432/mydatabase
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmedkalwar38@gmail.com
    password: knsmrwjycnpkceuc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://service-registery:8772/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true



