# Server settings
server:
  port: 8088
  ssl:
      enabled: false

  provider:
    host: https://localhost:9443




# Database configuration
spring:
#  kafka:
#    topic:
#      name: otp-topic
#    producer:
#      bootstrap-servers: kafka:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://192.168.0.196:5432/mydatabase
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
#      ddl-auto: update
    show-sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmedkalwar38@gmail.com
    password: knsmrwjycnpkceuc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8772/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

    #    wso2 implement
#        spring:
    security:
          oauth2:
            client:
              registration:
                wso2:
                  client-id: admin
                  client-secret: admin
                  scope: openid
                  authorization-grant-type: authorization_code
                  redirect-uri: "http://localhost:8080/login/oauth2/code/wso2"
                  client-name: WSO2
              provider:
                wso2:
                  authorization-uri: https://localhost:9443/oauth2/authorize
                  token-uri: https://localhost:9443/oauth2/token
                  user-info-uri: https://localhost:9443/oauth2/userinfo
                  jwk-set-uri: https://localhost:9443/oauth2/jwks
                  user-name-attribute: sub

                  spring:
                    main:
                      allow-bean-definition-overriding: true



