# Server settings
server:
  port: 8085

spring:
  # Application configuration
  application:
    name: Bill-Service

  # Database configuration
  datasource:
    url: jdbc:postgresql://192.168.0.196:5432/mydatabase
    username: postgres
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  # Kafka configuration
  kafka:
    topic:
      name: notification-topic
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers: localhost:9092
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

  #  kafka:
#    topic:
#      name: notification-topic
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: email-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#      properties:
#        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
#        spring.json.trusted.packages: "*"

  # Email configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ahmedkalwar38@gmail.com
    password: knsmrwjycnpkceuc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
